version: "3.9"

services:
  db_enterprise:
    image: mariadb:11.2.3
    restart: always
    environment:
      MARIADB_USER: springuser
      MARIADB_PASSWORD: ThePassword
      MARIADB_DATABASE: db_enterprise
      MARIADB_ROOT_PASSWORD: ThePassword
    #volumes:
    #  - ./data:/var/lib/mysql
    ports:
      - "3306:3306"
    container_name: db_enterprise
    labels:
      - "traefik.enable=false"

    networks:
      - softcont-network

  enterprises_management:
    image: jeserna/enterprises_management:latest
    #ports:
    #  - "8081:8080"
    environment:
      - DB_USERNAME=springuser
      - DB_PASSWORD=ThePassword
      - DB_URL=jdbc:mariadb://db_enterprise:3306/db_enterprise
      - SECURITY_USER=pablo
      - SECURITY_PASSWORD=1234
    depends_on:
      - db_enterprise
    container_name: enterprises_management
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.enterprises_management.rule=PathPrefix(`/enterprises`)"
      - "traefik.http.services.enterprises_management.loadbalancer.server.port=8080"
    networks:
      - softcont-network

networks:
  softcont-network:
    external: true
