version: "3.9"

services:
  db:
    image: mariadb:11.2.3
    restart: always
    environment:
      MARIADB_USER: springuser
      MARIADB_PASSWORD: ThePassword
      MARIADB_DATABASE: db_enterprise
      MARIADB_ROOT_PASSWORD: ThePassword
    #volumes:
    #  - ./data:/var/lib/mysql
    ports:
        - "3306:3306"
    container_name: db

  enterprises_management:
  
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_USERNAME=springuser
      - DB_PASSWORD=ThePassword
      - DB_URL=jdbc:mariadb://db:3306/db_enterprise
      - SECURITY_USER=pablo
      - SECURITY_PASSWORD=1234
    depends_on:
      - db
    container_name: enterprises_management
