version: "3"

services:
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_USER: springuser
      MARIADB_PASSWORD: ThePassword
      MARIADB_DATABASE: db_enterprise
      MARIADB_ROOT_PASSWORD: ThePassword
    #volumes:
    #  - ./data:/var/lib/mysql
    ports:
        - "3306:3306"
    container_name: db

  enterprises_management:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    container_name: enterprises_management
