spring:
  application:
    name: enterprises

  profiles:
    active:
    - ${PROFILE:dev}

  jpa:
    defer-datasource-initialization: true
    show-sql: true

  sql:
    init:
      mode: always

springdoc:
    swagger-ui:
      path: ${SWAGGER_PATH:/swagger-ui.html}

server:
  error:
    include-stacktrace: never