name: Java Maven Build & Docker Image Push

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

jobs:
  test:
    name: Build and Test Java with Maven
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Test with Maven
        run: mvn test

  docker:
    name: Build Docker image and push to Docker Hub
    runs-on: ubuntu-latest
    needs: test
    env:
      REPO_NAME: ${{ github.event.repository.name }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3



      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Get Previous tag
        id: previoustag
        uses: WyriHaximus/github-action-get-previous-tag@v1
        with:
          fallback: 1.0.0

      - name: Build the Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ env.REPO_NAME }}:${{ steps.previoustag.outputs.tag }} .

      - name: Tag the Docker image
        run: docker tag ${{ secrets.DOCKER_USERNAME }}/${{ env.REPO_NAME }}:${{ steps.previoustag.outputs.tag }} ${{ secrets.DOCKER_USERNAME }}/${{ env.REPO_NAME }}:latest

      - name: Push Docker image
        run: |
         docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.REPO_NAME }}:${{ steps.previoustag.outputs.tag }}
         docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.REPO_NAME }}:latest
